/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[301] =
    {   0,
        0,    0,   17,   16,   11,   14,    4,    1,   14,   14,
        5,    7,    8,   14,   14,   14,   14,   14,   14,   13,
       13,   14,   15,   14,   14,   14,   10,   14,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   14,   14,   11,   14,
        0,   11,    6,    0,    1,    0,   13,    0,    3,    2,
        0,    0,    0,   14,   14,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,    6,    0,
        2,    0,    0,   13,   12,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,    0,   13,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    9,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       10,   29,   11,   30,   31,   21,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   27,   41,   42,   43,   44,
       45,   46,   27,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   10,   56,   11,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    1,    1,
        4,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[306] =
    {   0,
        0,    0,  148, 1088,   56,  123,   60,    0,  120,   52,
     1088, 1088, 1088,  118,   51, 1088,   53,   48,   61,   64,
       69,  118, 1088,   71,  104,   73,   80,  100,   83,   90,
       88,   92,  107,   95,  100,  102,  132,  137,   85,  139,
      141,  143,  149,  153,  160,  172,   56, 1088,  205, 1088,
       86,  210,  214,  113,    0,  147,  202,  204, 1088,    0,
      156,  214,    0,   63,   58,  162,  175,  180,  216,  218,
      223,  225,  227,  231,  229,  240,  235,  242,  244,  246,
      251,  256,  258,  262,  267,  276,  282,  287,  289,  291,
      294,  296,  298,  302,  304,  310,  315,  319,  326,  334,

      336,  338,  345,  342,  348,  352,  357,  359, 1088,  385,
        0,  389,  354,  393,    0,  395,  369,  361,  398,  402,
      404,  408,  415,  412,  417,  421,  423,  425,  427,  442,
      444,  447,  452,  455,  457,  463,  465,  467,  471,  475,
      480,  477,  487,  489,  492,  494,  496,  498,  502,  504,
      506,  512,  517,  519,  527,  530,  534,  538,  541,  543,
      549,  551,  554,  556,  558,  562,  569,  572,  575,  577,
      581,  583,  585,  587,  589,  594,  598,  596,  600,  606,
      609,  616,  621,  626,  630,  632,  634,  636,  644,  638,
      651,  655,  657,  661,  663,  669,  671,  673,  677,  680,

      685,  694,  698,  701,  705,  707,  709,  712,  714,  717,
      722,  726,  729,  733,  735,  737,  748,  754,  758,  760,
      762,  764,  766,  768,  770,  772,  776,  781,  784,  795,
      786,  797,  804,  806,  809,  813,  815,  817,  819,  824,
      826,  832,  834,  838,  842,  845,  849,  851,  853,  856,
      861,  864,  868,  871,  873,  881,  883,  885,  890,  892,
      900,  896,  902,  905,  907,  909,  915,  917,  919,  922,
      930,  932,  935,  939,  943,  949,  951,  954,  956,  958,
      962,  966,  974,  979,  981,  983,  985,  987,  993, 1000,
     1002, 1006, 1008, 1012, 1014, 1017, 1020, 1022, 1024, 1088,

     1073, 1077, 1079, 1083,   67
    } ;

static yyconst short int yy_def[306] =
    {   0,
      300,    1,  300,  300,  300,  300,  301,  302,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  303,  300,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  300,  300,  300,  300,
      301,  301,  300,  301,  302,  300,  300,  300,  300,  304,
      300,  300,  305,  300,  300,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  300,  300,
      304,  300,  300,  300,  305,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  300,  300,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,    0,

      300,  300,  300,  300,  300
    } ;

static yyconst short int yy_nxt[1146] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   27,    4,   28,
       27,   27,   29,   30,   31,   32,   33,   34,   27,   35,
       27,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   27,   27,   27,   47,   48,   49,   49,   50,
       49,   52,   52,   50,   53,   58,   58,   50,   56,  115,
       57,   57,   59,   50,   50,   50,   50,   60,   50,   61,
       50,   57,   57,   50,   61,   50,   57,   57,   54,   62,
      109,   63,   64,   50,   62,   50,   65,   66,   66,   62,

       66,   66,   66,   66,   62,   66,   66,   66,   66,   66,
       66,   50,   66,   66,   54,  300,   63,   66,   66,   66,
       66,   70,   50,   74,   66,   66,   50,   68,   71,   69,
       91,   72,   75,   77,   73,   78,   85,   50,   80,   84,
       50,   76,   50,   86,   79,   50,   87,  300,   81,   66,
       66,   82,  300,   83,   66,   66,   66,   66,   66,   66,
       66,   66,  300,   88,   58,   58,   66,   66,   89,  300,
       66,   66,   90,  112,  112,  300,   94,   66,   66,   66,
       66,   95,   96,  300,   99,   92,  300,  100,   93,   66,
       66,   97,   66,   66,   98,  101,  103,   66,   66,  105,

      104,  300,  102,  300,  106,  107,   49,   49,  300,   49,
      108,   52,   52,  300,   53,   49,   49,   61,   49,   57,
       57,   58,   58,  300,  116,  300,  113,   62,  113,  110,
      300,  114,  114,   66,   66,   66,   66,   62,   54,  110,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
      300,  117,   66,   66,  120,  300,  121,   66,   66,   66,
       66,   66,   66,   66,   66,  118,  119,  123,   66,   66,
      122,  300,  124,   66,   66,   66,   66,  300,  125,   66,
       66,  300,  127,  126,   66,   66,  300,  131,  300,  129,
      300,  128,  130,   66,   66,  132,  300,  133,  300,   66,

       66,  300,   85,  300,   66,   66,   66,   66,   66,   66,
      134,   66,   66,   66,   66,   66,   66,  135,  300,   66,
       66,   66,   66,  300,   85,  136,  137,   66,   66,  139,
      142,  138,   66,   66,  300,  140,   66,   66,  300,  143,
      141,  144,   85,   66,   66,  300,  149,  147,  146,  300,
      145,   66,   66,   66,   66,   66,   66,  300,  151,   66,
       66,  150,   66,   66,  148,   66,   66,  300,  152,   66,
       66,  114,  114,  153,   66,   66,   66,   66,   66,   66,
      154,  159,  300,  156,  157,  155,   66,   66,  300,   85,
      300,  161,  158,  162,  160,  163,   85,  165,  164,  165,

      167,  300,  166,  166,   61,  300,  112,  112,   61,  300,
      114,  114,   66,   66,   62,   66,   66,  300,   62,   66,
       66,   66,   66,  300,   62,   66,   66,  300,   62,   66,
       66,  168,   66,   66,   66,   66,   85,  300,   66,   66,
       66,   66,   66,   66,   66,   66,  172,  174,   85,  175,
      300,  169,  176,  300,  173,  170,  171,  300,   85,   66,
       66,   66,   66,  300,   66,   66,  300,   85,  177,   66,
       66,  178,   66,   66,   66,   66,  300,  179,  181,  300,
       66,   66,   66,   66,   66,   66,  300,  182,   66,   66,
      300,  180,   66,   66,   66,   66,  183,   66,   66,   85,

      184,  300,  185,  300,   66,   66,   66,   66,   85,   66,
       66,   66,   66,   66,   66,   66,   66,  186,  189,   66,
       66,   66,   66,   66,   66,  187,  190,  300,  188,   66,
       66,  300,  191,  195,   66,   66,   66,   66,  300,  194,
      193,  192,  300,  197,   66,   66,  300,   66,   66,  300,
      196,   66,   66,  198,  199,   66,   66,  200,   66,   66,
       66,   66,   85,  201,   85,  202,   66,   66,   66,   66,
      300,   66,   66,   66,   66,  166,  166,  204,  203,  166,
      166,  300,  207,   85,  205,  208,   66,   66,  300,   66,
       66,  206,   66,   66,   66,   66,  300,  209,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,  300,   85,
       85,   66,   66,   66,   66,   66,   66,   66,   66,  300,
      210,  300,   85,   66,   66,   85,   66,   66,  212,  300,
      214,  300,  211,   66,   66,  213,  215,  216,   66,   66,
      300,   85,  217,   66,   66,  300,  218,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   85,  300,  219,
      221,   66,   66,  224,  220,  225,  300,  222,   66,   66,
      300,  226,   66,   66,   66,   66,  300,  223,   66,   66,
       66,   66,  300,  227,  300,  228,   66,   66,   66,   66,
       66,   66,  300,  232,   66,   66,  231,   66,   66,  229,

      300,  230,   66,   66,  300,   85,  236,  233,  234,  300,
      237,   66,   66,  300,  235,   66,   66,  300,   66,   66,
      300,  238,   66,   66,   66,   66,   66,   66,  239,   66,
       66,   66,   66,  240,   66,   66,   85,  241,  242,   66,
       66,   85,   85,   66,   66,  300,   66,   66,  300,   85,
       66,   66,   66,   66,   66,   66,  243,  244,  245,  300,
      246,   85,  300,  247,   85,   66,   66,  300,   85,  300,
      249,   66,   66,  300,  248,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,  300,   85,   66,   66,   85,   85,   85,   66,   66,

      300,   66,   66,   66,   66,  255,  250,  300,  251,   85,
      300,  252,   66,   66,   66,   66,  253,  300,  254,  257,
       85,   66,   66,   66,   66,  300,   66,   66,  300,  256,
       66,   66,   66,   66,   66,   66,   66,   66,   85,  258,
       85,   66,   66,   66,   66,   85,   85,  300,  259,   66,
       66,   66,   66,   85,  260,   66,   66,  261,   85,   66,
       66,   85,   66,   66,  300,  263,   66,   66,   66,   66,
       66,   66,  265,   66,   66,  262,  300,  264,   66,   66,
      300,   66,   66,  300,  267,   66,   66,  300,   66,   66,
       66,   66,  268,  300,  266,  271,  300,   85,   66,   66,

       66,   66,   66,   66,  270,  269,   85,   66,   66,   66,
       66,  300,  272,   66,   66,  276,  274,   66,   66,   66,
       66,  273,   66,   66,   66,   66,   66,   66,   85,  275,
      300,  279,   66,   66,   66,   66,   66,   66,  277,   66,
       66,  300,  278,   85,   85,  281,  280,   66,   66,   66,
       66,  282,   66,   66,  300,   85,   66,   66,  300,   85,
       66,   66,  300,  283,  300,   85,   66,   66,   66,   66,
      284,   66,   66,   66,   66,   66,   66,  300,   85,   66,
       66,  300,  286,   66,   66,   85,   85,  300,  285,   85,
       85,   66,   66,   85,  300,  287,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,  300,  288,  300,   85,
       66,   66,  300,   85,  290,  300,  291,   66,   66,   66,
       66,  300,   85,   66,   66,   66,   66,  289,  292,   66,
       66,   66,   66,  300,   66,   66,  300,   66,   66,   66,
       66,   66,   66,  300,  296,  300,  300,  293,  300,  294,
      297,  298,  300,  300,  295,  300,   85,  300,  300,  300,
       85,  300,  300,  300,  300,  300,  300,  300,  300,  299,
      300,  300,   85,   51,   51,   51,   51,   55,  300,   55,
       55,   67,   67,  111,  300,  111,  111,    3,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300
    } ;

static yyconst short int yy_chk[1146] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,   10,
        5,    7,    7,   15,    7,   18,   18,   17,   17,  305,
       17,   17,   19,   15,   10,   17,   17,   19,   47,   20,
       65,   20,   20,   19,   21,   64,   21,   21,    7,   20,
       51,   20,   24,   24,   21,   26,   26,   27,   27,   20,

       29,   29,   39,   39,   21,   31,   31,   30,   30,   32,
       32,   47,   34,   34,   51,   54,   20,   35,   35,   36,
       36,   30,   28,   31,   33,   33,   25,   29,   30,   29,
       39,   30,   31,   32,   30,   32,   35,   22,   33,   34,
       14,   31,    9,   35,   32,    6,   36,    3,   33,   37,
       37,   33,    0,   33,   38,   38,   40,   40,   41,   41,
       42,   42,    0,   37,   56,   56,   43,   43,   38,    0,
       44,   44,   38,   61,   61,    0,   41,   45,   45,   66,
       66,   42,   42,    0,   43,   40,    0,   43,   40,   46,
       46,   42,   67,   67,   42,   43,   44,   68,   68,   45,

       44,    0,   43,    0,   45,   46,   49,   49,    0,   49,
       46,   52,   52,    0,   52,   53,   53,   57,   53,   57,
       57,   58,   58,    0,   68,    0,   62,   57,   62,   58,
        0,   62,   62,   69,   69,   70,   70,   57,   52,   58,
       71,   71,   72,   72,   73,   73,   75,   75,   74,   74,
        0,   69,   77,   77,   71,    0,   72,   76,   76,   78,
       78,   79,   79,   80,   80,   70,   70,   74,   81,   81,
       73,    0,   74,   82,   82,   83,   83,    0,   75,   84,
       84,    0,   77,   76,   85,   85,    0,   80,    0,   79,
        0,   78,   79,   86,   86,   81,    0,   83,    0,   87,

       87,    0,   82,    0,   88,   88,   89,   89,   90,   90,
       84,   91,   91,   92,   92,   93,   93,   86,    0,   94,
       94,   95,   95,    0,   86,   87,   88,   96,   96,   91,
       93,   89,   97,   97,    0,   92,   98,   98,    0,   94,
       92,   94,   90,   99,   99,    0,   97,   96,   95,    0,
       94,  100,  100,  101,  101,  102,  102,    0,   98,  104,
      104,   97,  103,  103,   96,  105,  105,    0,   99,  106,
      106,  113,  113,  100,  107,  107,  108,  108,  118,  118,
      100,  104,    0,  102,  103,  101,  117,  117,    0,  101,
        0,  106,  103,  106,  105,  107,  118,  110,  108,  110,

      117,    0,  110,  110,  112,    0,  112,  112,  114,    0,
      114,  114,  116,  116,  112,  119,  119,    0,  114,  120,
      120,  121,  121,    0,  112,  122,  122,    0,  114,  124,
      124,  119,  123,  123,  125,  125,  116,    0,  126,  126,
      127,  127,  128,  128,  129,  129,  123,  124,  120,  125,
        0,  121,  126,    0,  123,  122,  122,    0,  127,  130,
      130,  131,  131,    0,  132,  132,    0,  128,  129,  133,
      133,  129,  134,  134,  135,  135,    0,  130,  132,    0,
      136,  136,  137,  137,  138,  138,    0,  133,  139,  139,
        0,  131,  140,  140,  142,  142,  135,  141,  141,  134,

      136,    0,  138,    0,  143,  143,  144,  144,  137,  145,
      145,  146,  146,  147,  147,  148,  148,  139,  142,  149,
      149,  150,  150,  151,  151,  140,  143,    0,  141,  152,
      152,    0,  144,  148,  153,  153,  154,  154,    0,  147,
      146,  145,    0,  150,  155,  155,    0,  156,  156,    0,
      149,  157,  157,  150,  151,  158,  158,  152,  159,  159,
      160,  160,  155,  154,  153,  156,  161,  161,  162,  162,
        0,  163,  163,  164,  164,  165,  165,  158,  157,  166,
      166,    0,  162,  161,  159,  163,  167,  167,    0,  168,
      168,  160,  169,  169,  170,  170,    0,  164,  171,  171,

      172,  172,  173,  173,  174,  174,  175,  175,    0,  167,
      168,  176,  176,  178,  178,  177,  177,  179,  179,    0,
      171,    0,  169,  180,  180,  170,  181,  181,  173,    0,
      175,    0,  172,  182,  182,  174,  176,  177,  183,  183,
        0,  180,  178,  184,  184,    0,  179,  185,  185,  186,
      186,  187,  187,  188,  188,  190,  190,  181,    0,  182,
      184,  189,  189,  186,  183,  187,    0,  184,  191,  191,
        0,  188,  192,  192,  193,  193,    0,  185,  194,  194,
      195,  195,    0,  189,    0,  190,  196,  196,  197,  197,
      198,  198,    0,  195,  199,  199,  194,  200,  200,  191,

        0,  192,  201,  201,    0,  193,  198,  195,  196,    0,
      199,  202,  202,    0,  197,  203,  203,    0,  204,  204,
        0,  200,  205,  205,  206,  206,  207,  207,  202,  208,
      208,  209,  209,  202,  210,  210,  201,  202,  204,  211,
      211,  203,  205,  212,  212,    0,  213,  213,    0,  209,
      214,  214,  215,  215,  216,  216,  206,  207,  208,    0,
      210,  212,    0,  211,  213,  217,  217,    0,  214,    0,
      216,  218,  218,    0,  215,  219,  219,  220,  220,  221,
      221,  222,  222,  223,  223,  224,  224,  225,  225,  226,
      226,    0,  219,  227,  227,  220,  217,  218,  228,  228,

        0,  229,  229,  231,  231,  226,  221,    0,  222,  227,
        0,  223,  230,  230,  232,  232,  224,    0,  225,  229,
      231,  233,  233,  234,  234,    0,  235,  235,    0,  228,
      236,  236,  237,  237,  238,  238,  239,  239,  230,  234,
      233,  240,  240,  241,  241,  232,  235,    0,  238,  242,
      242,  243,  243,  237,  239,  244,  244,  241,  240,  245,
      245,  236,  246,  246,    0,  243,  247,  247,  248,  248,
      249,  249,  245,  250,  250,  242,    0,  244,  251,  251,
        0,  252,  252,    0,  248,  253,  253,    0,  254,  254,
      255,  255,  249,    0,  246,  252,    0,  247,  256,  256,

      257,  257,  258,  258,  251,  250,  254,  259,  259,  260,
      260,    0,  253,  262,  262,  258,  256,  261,  261,  263,
      263,  255,  264,  264,  265,  265,  266,  266,  260,  257,
        0,  262,  267,  267,  268,  268,  269,  269,  259,  270,
      270,    0,  261,  263,  266,  267,  264,  271,  271,  272,
      272,  269,  273,  273,    0,  265,  274,  274,    0,  270,
      275,  275,    0,  271,    0,  268,  276,  276,  277,  277,
      273,  278,  278,  279,  279,  280,  280,    0,  272,  281,
      281,    0,  276,  282,  282,  274,  277,    0,  275,  278,
      279,  283,  283,  280,    0,  281,  284,  284,  285,  285,

      286,  286,  287,  287,  288,  288,    0,  282,    0,  283,
      289,  289,    0,  284,  286,    0,  287,  290,  290,  291,
      291,    0,  288,  292,  292,  293,  293,  285,  289,  294,
      294,  295,  295,    0,  296,  296,    0,  297,  297,  298,
      298,  299,  299,    0,  295,    0,    0,  290,    0,  291,
      296,  297,    0,    0,  292,    0,  293,    0,    0,    0,
      294,    0,    0,    0,    0,    0,    0,    0,    0,  298,
        0,    0,  299,  301,  301,  301,  301,  302,    0,  302,
      302,  303,  303,  304,    0,  304,  304,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "a.lex"
#define INITIAL 0
#line 2 "a.lex"
int wordCount = 0;
int numcount = 0;
#define N 100000 
char stack[N];
int top=0;
#line 720 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 14 "a.lex"

#line 869 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1088 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "a.lex"
{printf("%s\n",yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "a.lex"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "a.lex"
{
	int c1=0,c2=input(),flag=0;
	while(1){
		if(c2==EOF)break;
		if(c1=='*'&c2=='/'){
			flag=1;
			break;
		}
		c1=c2;
		c2=input();
	}
	if(flag==0)printf("/**/²»Æ¥Åä\n");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "a.lex"
{
	char s[10000];
	s[0]='"';
	int len=1,flag=0;
	s[len]=input();
	while(1){
		if(s[len]==EOF)break;
		if(s[len]=='"'&&s[len-1]!='\\'){
			flag=1;
			break;
		}
		++len;
		s[len]=input();
	}
	if(flag==1){
		printf("(%d,\"%s\")\n",4,s);
	}
	else{
		printf("\"\"²»Æ¥Åä\n");
		return;
	}
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "a.lex"
{
	char s[10000];
	s[0]='\'';
	int len=1,flag=0;
	s[len]=input();
	while(1){
		if(s[len]==EOF)break;
		if(s[len]=='\''&&s[len-1]!='\\'){
			flag=1;
			break;
		}
		++len;
		s[len]=input();
	}
	if(flag==1){
		printf("(%d,\"%s\")\n",4,s);
	}
	else{
		printf("''²»Æ¥Åä\n");
		return;
	}
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "a.lex"
{printf("(%d,\"%s\")\n",3,yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "a.lex"
{stack[top++]=yytext[0];printf("(%d,\"%s\")\n",5,yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "a.lex"
{
	if(top>0){
		char c=stack[top-1],d=yytext[0];
		if(c=='('&&d==')'||c=='['&&d==']'||c=='{'&&d=='}'){
			--top;
			printf("(%d,\"%s\")\n",5,yytext);
		}
		else {
			printf("À¨ºÅ²»Æ¥Åä\n");
			return;
		}
	}
	else {
		printf("À¨ºÅ²»Æ¥Åä\n");
		return;
	}
	
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "a.lex"
{printf("(%d,\"%s\")\n",1,yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "a.lex"
{ wordCount++; printf("(%d,\"%s\")\n",2,yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 96 "a.lex"
{}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "a.lex"
{printf("(%d,\"%s\")\n",3,yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "a.lex"
{printf("(%d,\"%s\")\n",3,yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "a.lex"
{printf("(%d,\"%s\")\n",4,yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "a.lex"
{printf("(%d,\"%s\")\n",5,yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "a.lex"
ECHO;
	YY_BREAK
#line 1103 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 101 "a.lex"


int main()
{
printf("ok1\n");

yylex(); /* start the  analysis*/

printf("ok2\n");
if(top!=0)printf("À¨ºÅ²»Æ¥Åä\n");
printf(" No of words: %d\n  number: %d\n", wordCount, numcount);
return 0;

}

int yywrap()
{
return 1;
}
